---
apiVersion: v1
kind: Pod
metadata:
  name: probe-container
spec:
  containers:
    - name: nginxcontainer
      image: nginx:latest
      livenessProbe:
        initialDelaySeconds: 10
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 30
        timeoutSeconds: 60
        tcpSocket:
          port: 8000
      ports:
        - name: nginxport
          protocol: TCP
          containerPort: 8000
      readinessProbe:
        initialDelaySeconds: 10
        failureThreshold: 3
        successThreshold: 5
        periodSeconds: 30
        timeoutSeconds: 60
        httpGet:
          path: /docs
          port: 8000
      resources:
        requests:
          memory: 120M
          cpu: 250m
        limits:
          memory: 250M
          cpu: 1000m
      startupProbe:
        initialDelaySeconds: 10
        failureThreshold: 3
        successThreshold: 1
        periodSeconds: 30
        timeoutSeconds: 60
        tcpSocket:
          port: 8000